### ISSUE TITLE
System.NotSupportedException: The ServiceProvider implementation has changed; please submit

### ISSUE THREAD

**Issue by hzy-6** [inversionhourglass/DependencyInjection.StaticAccessor#1]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/50e6ab14-d0f3-4bac-9173-2d391b62bf81">

<img width="1653" alt="image" src="https://github.com/user-attachments/assets/36a60a34-ea5d-4a8a-a76f-b3e1e5a825ff">
报错位置：
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/a8c13631-735b-41c5-bda8-f3cb692c1342">
可能需要加锁，或者防止集合变更修改问题。

**Comment by inversionhourglass** [comment]
你的项目的.NET SDK是什么版本的，DependencyInjection.StaticAccessor 需要不同的.NET版本引用不同的NuGet版本。

[版本号说明](https://github.com/inversionhourglass/DependencyInjection.StaticAccessor?tab=readme-ov-file#%E7%89%88%E6%9C%AC%E5%8F%B7%E8%AF%B4%E6%98%8E)

> 引用NuGet时请保持主版本号与你引用的Microsoft.Extensions.*保持一致

**Comment by hzy-6** [comment]
我是 net8

**Comment by inversionhourglass** [comment]
.NET 8.0 引用 DependencyInjection.StaticAccessor 8.0版本，如果你引用的是8.0版本，你看下你引用的官方`Microsoft.Extensions`系列NuGet是不是8.x版本。如果是，你把`Microsoft.Extensions`系列的具体版本号发出来

**Comment by hzy-6** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e11c0137-e67b-4bbd-968c-6a39643e52b4">

**Comment by inversionhourglass** [comment]
9.0的需要降级到8.0，6.0的你看能不能升到8.0，Microsoft.Extensions系列最好保证大版本一致。

9.0版本近期会更新，如果你确实需要用 Microsoft.Extensions 9.0，需要再等几天。

**Comment by hzy-6** [comment]
这个对版本依赖有点高

**Comment by hzy-6** [comment]
上面截图是错的，我是 net8 不可能使用 net9 的包，我刚查了没有 高版本的。我可以调试代码，协助你找到问题

**Comment by inversionhourglass** [comment]
其实主要是对`Microsoft.Extensions.DependencyInjection`的版本有要求，其他的NuGet的版本是建议保持大版本一致。这个没办法，强依赖官方内部实现，如果官方的依赖注入实现能稳定保持不变，这个依赖限制也就没有了。

今天晚些时候将会发布9.0预发版，如果你需要使用 `Microsoft.Extensions` 9.0版本，之后可以先更新到预发版，正式版还需要一些测试。

**Comment by inversionhourglass** [comment]
> 上面截图是错的，我是 net8 不可能使用 net9 的包，我刚查了没有 高版本的。我可以调试代码，协助你找到问题

.NET 8.0 是可以使用9.0的包的，9.0的包支持`netstandard2.0`

![image](https://github.com/user-attachments/assets/afee6546-3e26-488b-a796-00aa805183e9)

**Comment by hzy-6** [comment]
嗯，那就等更新吧，里面9 的包都是 隐式包 不好降级

**Comment by inversionhourglass** [comment]
9.0 preview 版本已发布，你更新试试，正式版还要几天

**Comment by hzy-6** [comment]
6啊 晚点我试试

**Comment by hzy-6** [comment]
程序可以正常启动没有报错了。但还未验证服务获取，暂时先关闭
